local phenix = require("phenix_nvim")
assert(type(phenix.toggle) == "function")
assert(type(phenix.send) == "function")
assert(type(phenix.reference) == "function")
assert(type(phenix.choose_session) == "function")
assert(type(phenix.authenticate) == "function")
assert(type(phenix.choose_selection) == "function")
assert(phenix.choose_model == nil)
assert(phenix.choose_routing_profile == nil)

local config = require("phenix_nvim.config").get()
assert(type(config.command) == "string" and config.command ~= "")
assert(config.command ~= "phenix-acp", "Nix package must inject the packaged phenix-acp runtime")
assert(vim.fn.executable(config.command) == 1, "packaged phenix-acp runtime must be executable")

assert(vim.fn.exists(":PhenixToggle") == 2)
assert(vim.fn.exists(":PhenixSend") == 2)
assert(vim.fn.exists(":PhenixAuth") == 2)
assert(vim.fn.exists(":PhenixSelect") == 2)
assert(vim.fn.exists(":PhenixModel") == 0)
assert(vim.fn.exists(":PhenixRoute") == 0)

local statusline = require("phenix.bars.defaults.statusline")
assert(type(statusline.phenix.hl()) == "string")
assert(type(statusline.phenix.text()) == "string")

phenix.disconnect()
