name: Propagate lock

on:
  push:
    branches:
      - chore/propagate-phenix-ai-nvim-be8e6618

permissions:
  contents: read

jobs:
  generate-lock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      - uses: cachix/install-nix-action@a49548c11d9846ad46ecc0115273879b045f001c # v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - name: Refresh phenix-ai.nvim lock
        run: nix flake update phenix-ai-nvim
      - name: Emit lock
        run: |
          echo PHENIX_LOCK_BEGIN
          base64 -w0 flake.lock
          echo
          echo PHENIX_LOCK_END
